# Introduction

The long term goal of the National Wildlife Refuge System (NWRS) Water Resource Inventory and Assessment (WRIA) effort is to provide up-to-date, accurate, reconnaissance-level data on water quantity and quality to support NWRS management planning and management actions to fulfill the NWRS mission and individual refuge purposes and management goals. An accurate water resources inventory is essential to prioritize issues and tasks, and to take prescriptive actions that are consistent with the established purposes of the refuge. WRIAs evaluate significant water resources (including rivers and streams, lakes and ponds, springs, wetlands, and groundwater), known water quality issues, water management infrastructure and practices, water rights, threats to water supplies, and other water resource issues for each site. 

This Water Resource Inventory (WRI) Report for Felsenthal National Wildlife Refuge (Felsenthal NWR or “the refuge”) summarizes available information relevant to refuge water resources, completing the first step of the WRIA process for the refuge. Major topics addressed in this report include the natural setting of the refuge (topography, climate, geology, soils, hydrology), impacts of development and climate change, significant water resources and associated infrastructure within the refuge, past and current water monitoring activities on and near the refuge, water quality information, and state water use regulatory framework. Information was compiled from publicly available reports, databases, and geospatial datasets from federal, state, and local agencies; published research reports; websites maintained by government agencies, academic institutions, and non-governmental organizations; and from files and geospatial data layers maintained by the refuge. 

This WRI report is presented on two scales: intermediate (within a Region of Hydrologic Influence (RHI) encompassing the refuge), and local (within the NWR). The WRI is the first step in the completion of a Water Resources Inventory and Assessment (WRIA). The inventory and assessment process continues with data assimilation at the local level and the assessment of key water resource issues of concern (threats or stressors) and needs. The WRIA report will synthesize the intermediate and local water resources inventory data and provide a summary of the threats and needs associated with water resources for ongoing water resource management and strategy development.

## Document Organization

This WRI report is partitioned into several categories and sub-categories according to a nationally adopted format for conducting water resource inventory and assessments through the US Fish & Wildlife Service (USFWS). This document follows this same format for easy inter-refuge operability, and is organized as follows:

- Facility information and habitats
- Natural Setting: topography, geology, hydrogeology, soils, hydrology and climate
- Inventory: water resources, water resource infrastructure, water quality, and water monitoring
- Assessment: threats and needs

The WRI report contains general information and maps describing the natural setting of the refuge. More detailed information can be found in the inventory section about water resources, water infrastructure, water quality, and water monitoring. The inventory also contains information about federal and state regulations for Felsenthal NWR and the surrounding area’s water resources. Some of the information, such as data sources and links to the information is provided in the Appendix.
 
## Map example

```{r map_demo, fig.cap = "An example interactive map."}
library(leaflet)
rand_lng = function(n = 10) rnorm(n, -83.36, .01)
rand_lat = function(n = 10) rnorm(n, 33.896, .01)
leaflet()%>% setView(-83.360730, 33.896008, zoom = 13) %>%
  addTiles() %>%
  addMarkers(rand_lng(), rand_lat(), popup = paste('A random letter', sample(LETTERS, 10)))
```
